export type SearchLanguage = "en" | "bn";

export const searchCopy = {
  en: {
    language: "Search language",
    english: "English",
    bengali: "বাংলা",
    problemLabel: "Describe the problem you want to solve",
    problemPlaceholder: "What problem are you trying to solve?",
    helper: "Describe what you need in your own words.",
    search: "Find solutions →",
    searchingButton: "Finding solutions…",
    searching: "Searching for useful solutions…",
    examplesTitle: "Try an example problem",
    examples: [
      "I need a free tool to edit PDF files",
      "I need help creating a professional resume",
      "I need an easy way to edit images",
      "I need tools to organize my studies",
      "I need software to manage a small business",
      "I need help planning a trip",
    ],
    searchError: "We couldn’t reach the solution service. Please try again.",
    publicLimitReached: "You have reached the public search limit. Please try again after the hourly reset.",
    publicProtectionUnavailable: "Public search protection is not ready. Please try again later.",
    retry: "Try again",
    solutionsFound: "Solutions found",
    resultFor: "Solutions for",
    foundOptions: "We found these options for",
    aiSummary: "AI summary",
    summaryUnavailable: "A short summary was not provided for this link.",
    visitWebsite: "Visit website",
    noResults: "No solutions were returned. Try describing the problem another way.",
    recentTitle: "Recent problems on this device",
    recentClear: "Clear list",
    recentRemove: "Remove recent problem",
    recentEmpty: "Your recent problems will appear here after you search.",
    recentDeviceOnly: "Stored only in this browser; it does not replace your account search history.",
    recentStorageError: "Browser storage is unavailable. Recent problems could not be updated.",
    category: "Category",
    categoryAny: "Any category",
    categories: {
      freelancing: "Freelancing",
      business: "Business",
      student: "Student",
      tech: "Tech",
    },
    copyLinks: "Copy all links",
    shareResult: "Share result",
    copied: "Links copied.",
    shared: "Share dialog opened.",
    shareCopied: "Sharing is unavailable; result copied instead.",
    shareError: "Could not copy or share this result.",
    helpful: "Helpful",
    notHelpful: "Not helpful",
    feedbackPrompt: "Was this useful?",
    feedbackSending: "Sending feedback…",
    feedbackSent: "Thanks for your feedback.",
    feedbackError: "Feedback could not be sent. Please try again later.",
    waitlistTitle: "Get updates on new solutions",
    waitlistDescription: "Join the waitlist to hear when we add new ways to solve problems.",
    waitlistPrivacy: "Your email is sent to our configured waitlist workflow for follow-up.",
    emailPlaceholder: "Your email address",
    joinWaitlist: "Notify me",
    joiningWaitlist: "Joining…",
    waitlistSuccess: "You’re on the list. Thank you!",
    waitlistError: "We couldn’t add you to the waitlist. Please try again later.",
    workspace: "Your workspace",
    workspaceTitle: "What can we help you solve?",
    workspaceDescription:
      "Describe what you need in your own words. Your searches and saved recommendations stay private to your account.",
    planAllowanceNeedsConfiguration: "Plan allowance needs configuration",
    monthlyAllowanceUnavailable: "Monthly search allowance unavailable",
    searchesRemaining: "{remaining} of {limit} searches left this month",
    usagePlan: "Usage & plan →",
    characterCount: "{count}/2,000 characters",
    limitReached:
      "You’ve reached this plan’s monthly search limit. Your allowance resets at the start of next month (UTC).",
    configurationError:
      "The search allowance for this plan has not been configured yet.",
    reviewPremium: "Review Premium",
    saved: "Saved ✓",
    saving: "Saving…",
    save: "☆ Save",
    saveError: "Could not save this solution.",
  },
  bn: {
    language: "অনুসন্ধানের ভাষা",
    english: "English",
    bengali: "বাংলা",
    problemLabel: "আপনি যে সমস্যার সমাধান খুঁজছেন তা লিখুন",
    problemPlaceholder: "আপনি কোন সমস্যার সমাধান খুঁজছেন?",
    helper: "আপনার প্রয়োজনটি নিজের ভাষায় বর্ণনা করুন।",
    search: "সমাধান খুঁজুন →",
    searchingButton: "সমাধান খোঁজা হচ্ছে…",
    searching: "আপনার জন্য উপযোগী সমাধান খোঁজা হচ্ছে…",
    examplesTitle: "উদাহরণ হিসেবে চেষ্টা করুন",
    examples: [
      "PDF ফাইল সম্পাদনার জন্য একটি বিনামূল্যের টুল চাই",
      "পেশাদার জীবনবৃত্তান্ত তৈরিতে সাহায্য চাই",
      "ছবি সম্পাদনার সহজ উপায় চাই",
      "পড়াশোনা গুছিয়ে রাখার টুল চাই",
      "ছোট ব্যবসা পরিচালনার সফটওয়্যার চাই",
      "ভ্রমণের পরিকল্পনা করতে সাহায্য চাই",
    ],
    searchError: "সমাধান সেবার সঙ্গে সংযোগ করা যায়নি। আবার চেষ্টা করুন।",
    publicLimitReached: "আপনি পাবলিক অনুসন্ধানের সীমায় পৌঁছেছেন। ঘণ্টাভিত্তিক সীমা পুনরায় চালু হলে আবার চেষ্টা করুন।",
    publicProtectionUnavailable: "পাবলিক অনুসন্ধান সুরক্ষা এখনো প্রস্তুত নয়। পরে আবার চেষ্টা করুন।",
    retry: "আবার চেষ্টা করুন",
    solutionsFound: "সমাধান পাওয়া গেছে",
    resultFor: "আপনার সমস্যার সমাধান",
    foundOptions: "এই সমস্যার জন্য আমরা কিছু বিকল্প পেয়েছি:",
    aiSummary: "এআই সারাংশ",
    summaryUnavailable: "এই লিংকের জন্য সংক্ষিপ্ত সারাংশ দেওয়া হয়নি।",
    visitWebsite: "ওয়েবসাইট দেখুন",
    noResults: "কোনো সমাধান পাওয়া যায়নি। সমস্যাটি অন্যভাবে বর্ণনা করে দেখুন।",
    recentTitle: "এই ডিভাইসের সাম্প্রতিক সমস্যা",
    recentClear: "তালিকা মুছুন",
    recentRemove: "সাম্প্রতিক সমস্যা সরান",
    recentEmpty: "অনুসন্ধান করার পর সাম্প্রতিক সমস্যাগুলো এখানে দেখা যাবে।",
    recentDeviceOnly: "শুধু এই ব্রাউজারে সংরক্ষিত; এটি আপনার অ্যাকাউন্টের অনুসন্ধান ইতিহাসের বিকল্প নয়।",
    recentStorageError: "ব্রাউজার স্টোরেজ পাওয়া যাচ্ছে না। সাম্প্রতিক সমস্যা আপডেট করা যায়নি।",
    category: "বিভাগ",
    categoryAny: "যেকোনো বিভাগ",
    categories: {
      freelancing: "ফ্রিল্যান্সিং",
      business: "ব্যবসা",
      student: "শিক্ষার্থী",
      tech: "প্রযুক্তি",
    },
    copyLinks: "সব লিংক কপি করুন",
    shareResult: "ফলাফল শেয়ার করুন",
    copied: "লিংক কপি হয়েছে।",
    shared: "শেয়ার ডায়ালগ খোলা হয়েছে।",
    shareCopied: "শেয়ার করা যাচ্ছে না; ফলাফল কপি করা হয়েছে।",
    shareError: "ফলাফল কপি বা শেয়ার করা যায়নি।",
    helpful: "সহায়ক",
    notHelpful: "সহায়ক নয়",
    feedbackPrompt: "এটি কি উপকারী ছিল?",
    feedbackSending: "মতামত পাঠানো হচ্ছে…",
    feedbackSent: "মতামতের জন্য ধন্যবাদ।",
    feedbackError: "মতামত পাঠানো যায়নি। পরে আবার চেষ্টা করুন।",
    waitlistTitle: "নতুন সমাধানের খবর পান",
    waitlistDescription: "সমস্যা সমাধানের নতুন উপায় যোগ হলে জানতে অপেক্ষমাণ তালিকায় যোগ দিন।",
    waitlistPrivacy: "পরবর্তীতে যোগাযোগের জন্য আপনার ইমেইল আমাদের কনফিগার করা অপেক্ষমাণ তালিকা ওয়ার্কফ্লোতে পাঠানো হবে।",
    emailPlaceholder: "আপনার ইমেইল ঠিকানা",
    joinWaitlist: "আমাকে জানান",
    joiningWaitlist: "যোগ করা হচ্ছে…",
    waitlistSuccess: "আপনি তালিকায় যুক্ত হয়েছেন। ধন্যবাদ!",
    waitlistError: "অপেক্ষমাণ তালিকায় যোগ করা যায়নি। পরে আবার চেষ্টা করুন।",
    workspace: "আপনার ওয়ার্কস্পেস",
    workspaceTitle: "কোন সমস্যার সমাধান খুঁজছেন?",
    workspaceDescription:
      "আপনার প্রয়োজনটি নিজের ভাষায় বর্ণনা করুন। আপনার অনুসন্ধান ও সংরক্ষিত সুপারিশ শুধু আপনার অ্যাকাউন্টে ব্যক্তিগত থাকে।",
    planAllowanceNeedsConfiguration: "প্ল্যানের অনুসন্ধান সীমা কনফিগার করা হয়নি",
    monthlyAllowanceUnavailable: "মাসিক অনুসন্ধান সীমা পাওয়া যাচ্ছে না",
    searchesRemaining: "এই মাসে আরও {remaining}/{limit}টি অনুসন্ধান করতে পারবেন",
    usagePlan: "ব্যবহার ও প্ল্যান →",
    characterCount: "{count}/২,০০০ অক্ষর",
    limitReached:
      "এই প্ল্যানের মাসিক অনুসন্ধান সীমা শেষ হয়েছে। পরের মাসের শুরুতে (UTC) সীমা আবার চালু হবে।",
    configurationError: "এই প্ল্যানের অনুসন্ধান সীমা এখনো কনফিগার করা হয়নি।",
    reviewPremium: "প্রিমিয়াম দেখুন",
    saved: "সংরক্ষিত ✓",
    saving: "সংরক্ষণ হচ্ছে…",
    save: "☆ সংরক্ষণ করুন",
    saveError: "এই সমাধানটি সংরক্ষণ করা যায়নি।",
  },
} as const;

export function getSearchCopy(language: SearchLanguage) {
  return searchCopy[language];
}
